import { Bot, Check, FileQuestion, X } from "lucide-react";
import React from "react";

const faqs = [
  {
    id: 1,
    question: "How do I return a product?",
    answer:
      "You can return products within 30 days of purchase. Items must be in original condition with all packaging. Contact customer support to initiate the return process.",
    confidenceLevel: "94%",
    source: "Product Manual",
    generatedBy: "AI Generated",
  },
  {
    id: 2,
    question: "What payment methods do you accept?",
    answer:
      "We accept all major credit cards (Visa, MasterCard, American Express), PayPal, and bank transfers for business accounts.",
    confidenceLevel: "91%",
    source: "Product Manual",
    generatedBy: "AI Generated",
  },
  {
    id: 3,
    question: "What are your customer support hours?",
    answer:
      "Our customer support team is available Monday through Friday from 9 AM to 6 PM EST. For urgent issues, use our online portal or emergency hotline.",
    confidenceLevel: "89%",
    source: "Customer Guidelines",
    generatedBy: "AI Generated",
  },
  {
    id: 4,
    question: "Can I upgrade my plan anytime?",
    answer:
      "Yes, you can upgrade your plan at any time from your account settings. Changes take effect immediately and you'll only pay the prorated difference.",
    confidenceLevel: "87%",
    source: "Customer Guidelines",
    generatedBy: "AI Generated",
  },
  {
    id: 5,
    question: "How long does account setup take?",
    answer:
      "Account setup takes just a few minutes. You'll need to provide your email, create a password, and verify your email address to get started.",
    confidenceLevel: "96%",
    source: "FAQ Database",
    generatedBy: "AI Generated",
  },
  {
    id: 6,
    question: "Is my data secure?",
    answer:
      "Yes, we use industry-standard encryption and security measures to protect your data. All information is stored securely and never shared with third parties.",
    confidenceLevel: "92%",
    source: "FAQ Database",
    generatedBy: "AI Generated",
  },
];

const AutoGeneratedFAQs = () => {
  return (
    <div className="w-full mx-auto p-4 sm:p-6 lg:p-8 bg-[#171717] rounded-2xl border border-gray-700 shadow-md mt-8">
      {/* Header row */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div className="flex space-x-4 mb-5">
          <div className="flex w-10 h-10 rounded-full bg-[#262626] justify-center items-center">
            <FileQuestion />
          </div>
          <div>
            <h3 className="text-white text-lg font-semibold leading-tight">
              Auto-Generated FAQs
            </h3>
            <span className="text-gray-400 text-xs md:text-sm">
              AI-powered FAQ creation from your content
            </span>
          </div>
        </div>

        <div className="flex flex-wrap gap-3">
          <button className="w-full sm:w-36 lg:w-40 h-10 bg-[#262626] rounded-lg text-sm text-white hover:bg-gray-700 transition">
            + Add FAQ
          </button>
          <button className="w-full sm:w-36 lg:w-40 h-10 bg-[#262626] rounded-lg text-sm text-white hover:bg-gray-700 transition">
            Generate More
          </button>
        </div>
      </div>

      {/* Content rows in grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
        {faqs.map((item) => (
          <div
            key={item.id}
            className="w-full bg-[#171717] rounded-2xl border border-gray-700 p-5 sm:p-6 lg:p-8 shadow-lg"
          >
            {/* top row */}
            <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
              <div className="flex items-center space-x-4">
                <div>
                  <h3 className="text-white text-base sm:text-lg font-semibold leading-tight">
                    {item.question}
                  </h3>
                </div>
              </div>

              {/* Right icon */}
              <div className="flex justify-between space-x-2">
                <Check className="w-5 h-5 text-gray-300 hover:text-white cursor-pointer transition" />
                <X className="w-5 h-5 text-gray-300 hover:text-white cursor-pointer transition" />
              </div>
            </div>

            {/* Description */}
            <p className="mt-4 sm:mt-5 text-xs sm:text-sm text-gray-300 leading-relaxed">
              {item.answer}
            </p>

            {/* Footer */}
            <div className="flex flex-wrap gap-3 sm:gap-5 mt-4 sm:mt-5 text-gray-400">
              <div className="flex items-center text-xs sm:text-sm">
                <Bot className="w-4 h-4 mr-1" />
                <p className="text-xs sm:text-sm">AI Generated</p>
              </div>
              <p className="ml-2">Confidence {item.confidenceLevel}</p>
              <p className="text-xs sm:text-sm">Source {item.source}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Bottom Row */}
      <div className="flex flex-col mt-5 md:flex-row md:items-center md:justify-between gap-4 w-full bg-[#171717] rounded-2xl border border-gray-700 p-5 sm:p-6 lg:p-8 shadow-lg">
        <div className="flex space-x-4 mb-5">
          <div className="flex w-10 h-10 rounded-full bg-[#262626] justify-center items-center">
            <FileQuestion />
          </div>
          <div>
            <h3 className="text-white text-lg font-semibold leading-tight">
              156 FAQs Generated
            </h3>
            <span className="text-gray-400 text-xs md:text-sm">
              Average Confidence: 91%
            </span>
          </div>
        </div>

        <div className="flex flex-wrap gap-3">
          <button className="w-full sm:w-36 lg:w-40 h-10 bg-[#262626] rounded-lg text-sm text-white hover:bg-gray-700 transition">
            Review All FAQs
          </button>
        </div>
      </div>
    </div>
  );
};

export default AutoGeneratedFAQs;
