"use client";
import React, { useState } from "react";

import CustomerSupportAgent from "@/_components/knowledgebase/CustomerSupportAgent";
import SetupProgress from "@/_components/knowledgebase/SetupProgress";
import ChooseYouContentSource, {
  Faq,
} from "@/_components/knowledgebase/ChooseYouContentSource";
import AIProcessing from "@/_components/knowledgebase/AIProcessing";
import ContentAnalysis from "@/_components/knowledgebase/ContentAnalysis";
import ContentPreview from "@/_components/knowledgebase/ContentPreview";
import AutoGeneratedFAQs from "@/_components/knowledgebase/AutoGeneratedFAQs";
import AdvancedProcessingSettings from "@/_components/knowledgebase/AdvancedProcessingSettings";
import IntegrationAndImportOptions from "@/_components/knowledgebase/IntegrationAndImportOptions";
import BottomButtons from "@/_components/knowledgebase/BottomButtons";
import TrainingPreview from "@/_components/knowledgebase/TrainingPreview";
import { toast } from "sonner";
import { useRouter } from "next/navigation";

const AddKnowledgeBasePage = () => {
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const [knowledgeBaseName, setKnowledgeBaseName] = useState("");
  const [websiteLinks, setWebsiteLinks] = useState<string[]>([]);
  const [faqs, setFaqs] = useState<Faq[]>([]);

  const [loading, setLoading] = useState<boolean>(false);

  const router = useRouter();

  /* handlers that already exist */
  const handleFilesSelected = (files: File[]) => setSelectedFiles(files);

  const handleCrawlerLink = (link: string) => {
    setWebsiteLinks((prev) => [...prev, link]); // add to array
  };

  const handleFaqsChange = (updated: Faq[]) => setFaqs(updated); // live stream

  const handleAddKnowledgeBase = async () => {
    if (!knowledgeBaseName.trim()) {
      toast.error("Name is required");
      return;
    }

    const hasSource =
      selectedFiles.length > 0 || websiteLinks.length > 0 || faqs.length > 0;

    if (!hasSource) {
      toast.error("At least one KB source is required");
      return;
    }

    /* ---------- build multipart body ---------- */
    setLoading(true);
    const fd = new FormData();
    fd.append("name", knowledgeBaseName);

    if (websiteLinks.length) fd.append("urls", JSON.stringify(websiteLinks));
    if (faqs.length) fd.append("faqs", JSON.stringify(faqs));
    selectedFiles.forEach((f) => fd.append("files", f));

    try {
      const res = await fetch("/api/ai/knowledgebase/add-kb", {
        method: "POST",
        body: fd,
      });

      const json = await res.json();

      if (!res.ok) {
        toast.error(json.error || "Unknown error");
        setLoading(false);
        return;
      }

      toast.success("Knowledge base created ✅");
      setLoading(false);

      router.push("/dashboard/app/ai/knowledgebase");
    } catch (err: any) {
      toast.error(err.message || "KB creation failed");
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen px-4 py-6 md:px-10 lg:px-16">
      {/* Header */}
      <h1 className="text-2xl md:text-3xl lg:text-4xl font-bold text-white text-center">
        Build Your AI Knowledge Base
      </h1>
      <p className="mt-3 text-sm md:text-base text-gray-300 text-center max-w-2xl mx-auto leading-relaxed">
        Transform your content into intelligent conversations. Upload files,
        import data, and train your AI agent with multiple content sources in
        just a few simple steps.
      </p>
      {/* ✅ Knowledge Base Name Input */}
      <div className="my-6">
        <p className="my-1 text-sm md:text-base text-gray-300 max-w-2xl">
          KnowledgeBase Name
        </p>
        <input
          type="text"
          value={knowledgeBaseName}
          onChange={(e) => setKnowledgeBaseName(e.target.value)}
          placeholder="Enter Knowledge Base Name"
          className="w-full max-w-md px-4 py-2 rounded-lg bg-[#1f1f1f] border border-gray-700 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#ef3e6d] transition"
        />
      </div>

      {/* CustomerSupportAgent Card */}
      {/* <CustomerSupportAgent /> */}

      {/* SetupProgress Card */}
      {/* <SetupProgress /> */}

      {/* Chooose Your Content Source */}
      <ChooseYouContentSource
        onFilesSelected={handleFilesSelected}
        onCrawlerLink={handleCrawlerLink}
        onFaqsSubmit={(f) => setFaqs(f)} // batch callback (when modal saves)
        onFaqsChange={handleFaqsChange} // live callback (on every edit)
      />

      {/* <UploadComponent /> */}

      {/* AI Processing & Content Analysis */}
      {/* <div className="flex flex-col lg:flex-row gap-6"> */}
      {/* <AIProcessing isUploading={isUploading} /> */}
      {/* <ContentAnalysis /> */}
      {/* </div> */}

      {/* Content Preview */}
      {/* <ContentPreview /> */}

      {/* AutoGeneratedFAQs */}
      {/* <AutoGeneratedFAQs knowledgebaseId={ids} userId={id} /> */}

      {/* AdvancedProcessingSettings */}
      {/* <AdvancedProcessingSettings /> */}

      {/* IntegrationAndImportOptions */}
      {/* <IntegrationAndImportOptions /> */}

      {/* TrainingPreview */}
      {/* <TrainingPreview /> */}
      {/* {selectedFileId ? (
        <TrainingPreview
          userId={id}
          fileId={selectedFileId} // Use the REAL file ID from upload
          fileName={"Uploaded Document"} // You might want to store the actual filename too
        />
      ) : (
        <div className="w-full mx-auto p-8 bg-[#171717] rounded-2xl border border-gray-700 shadow-md text-center">
          <p className="text-gray-400">
            Upload a file above to enable AI training
          </p>
        </div>
      )} */}

      {/* Bottom Buttons */}
      <BottomButtons
        handleAddKnowledgeBase={handleAddKnowledgeBase}
        loading={loading}
      />
    </div>
  );
};

export default AddKnowledgeBasePage;
