"use client";
import React, { useState } from "react";

import CustomerSupportAgent from "@/_components/knowledgebase/CustomerSupportAgent";
import SetupProgress from "@/_components/knowledgebase/SetupProgress";
import ChooseYouContentSource from "@/_components/knowledgebase/ChooseYouContentSource";
import AIProcessing from "@/_components/knowledgebase/AIProcessing";
import ContentAnalysis from "@/_components/knowledgebase/ContentAnalysis";
import ContentPreview from "@/_components/knowledgebase/ContentPreview";
import AutoGeneratedFAQs from "@/_components/knowledgebase/AutoGeneratedFAQs";
import AdvancedProcessingSettings from "@/_components/knowledgebase/AdvancedProcessingSettings";
import IntegrationAndImportOptions from "@/_components/knowledgebase/IntegrationAndImportOptions";
import BottomButtons from "@/_components/knowledgebase/BottomButtons";
import TrainingPreview from "@/_components/knowledgebase/TrainingPreview";

const AddKnowledgeBasePage = () => {
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const [knowledgeBaseName, setKnowledgeBaseName] = useState("");

  // ✅ This will be triggered when user selects or removes files
  const handleFilesSelected = (files: File[]) => {
    setSelectedFiles(files);
  };

  const handleCrawlerLink = (link: string) => {
    console.log("🌐 Crawler Link:", link);
    // 👉 You can store this link in state or send to backend
    // setKnowledgeBaseLinks((prev) => [...prev, link]);
  };

  const handleAddKnowledgeBase = () => {
    if (!knowledgeBaseName.trim() || selectedFiles.length === 0) return;

    console.log("Add Knowledge Base clicked", {
      selectedFiles,
      knowledgeBaseName,
    });
  };

  return (
    <div className="min-h-screen px-4 py-6 md:px-10 lg:px-16">
      {/* Header */}
      <h1 className="text-2xl md:text-3xl lg:text-4xl font-bold text-white text-center">
        Build Your AI Knowledge Base
      </h1>
      <p className="mt-3 text-sm md:text-base text-gray-300 text-center max-w-2xl mx-auto leading-relaxed">
        Transform your content into intelligent conversations. Upload files,
        import data, and train your AI agent with multiple content sources in
        just a few simple steps.
      </p>
      {/* ✅ Knowledge Base Name Input */}
      <div className="my-6">
        <p className="my-1 text-sm md:text-base text-gray-300 max-w-2xl">
          KnowledgeBase Name
        </p>
        <input
          type="text"
          value={knowledgeBaseName}
          onChange={(e) => setKnowledgeBaseName(e.target.value)}
          placeholder="Enter Knowledge Base Name"
          className="w-full max-w-md px-4 py-2 rounded-lg bg-[#1f1f1f] border border-gray-700 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#ef3e6d] transition"
        />
      </div>

      {/* CustomerSupportAgent Card */}
      {/* <CustomerSupportAgent /> */}

      {/* SetupProgress Card */}
      {/* <SetupProgress /> */}

      {/* Chooose Your Content Source */}
      <ChooseYouContentSource
        onFilesSelected={handleFilesSelected}
        onCrawlerLink={handleCrawlerLink}
        onFaqsSubmit={(faqs) => console.log("FAQs from modal:", faqs)}
      />

      {/* <UploadComponent /> */}

      {/* AI Processing & Content Analysis */}
      {/* <div className="flex flex-col lg:flex-row gap-6"> */}
      {/* <AIProcessing isUploading={isUploading} /> */}
      {/* <ContentAnalysis /> */}
      {/* </div> */}

      {/* Content Preview */}
      {/* <ContentPreview /> */}

      {/* AutoGeneratedFAQs */}
      {/* <AutoGeneratedFAQs knowledgebaseId={ids} userId={id} /> */}

      {/* AdvancedProcessingSettings */}
      {/* <AdvancedProcessingSettings /> */}

      {/* IntegrationAndImportOptions */}
      {/* <IntegrationAndImportOptions /> */}

      {/* TrainingPreview */}
      {/* <TrainingPreview /> */}
      {/* {selectedFileId ? (
        <TrainingPreview
          userId={id}
          fileId={selectedFileId} // Use the REAL file ID from upload
          fileName={"Uploaded Document"} // You might want to store the actual filename too
        />
      ) : (
        <div className="w-full mx-auto p-8 bg-[#171717] rounded-2xl border border-gray-700 shadow-md text-center">
          <p className="text-gray-400">
            Upload a file above to enable AI training
          </p>
        </div>
      )} */}

      {/* Bottom Buttons */}
      <BottomButtons handleAddKnowledgeBase={handleAddKnowledgeBase} />
    </div>
  );
};

export default AddKnowledgeBasePage;
